// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AlertsDTO { id: bigint, active: boolean | null, name: string | null, table: string | null, lookup: string | null, timing: number | null, warn: string | null, crit: string | null, info: string | null, where_clause: string | null, }