// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AlertsDTO { active: boolean | null, name: string, table: string, lookup: string, timing: number, warn: string, crit: string, info: string | null, host_uuid: string, cid: string, hostname: string, where_clause: string | null, }