// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ApiKey { id: bigint, key: string, host_uuid: string | null, customer_id: string, berta: string, }