// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CpuTimes { id: bigint, cuser: bigint, nice: bigint, system: bigint, idle: bigint, iowait: bigint, irq: bigint, softirq: bigint, steal: bigint, guest: bigint, guest_nice: bigint, host_uuid: string, created_at: string, }