// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Disk { id: bigint, disk_name: string, mount_point: string, total_space: bigint, avail_space: bigint, host_uuid: string, created_at: string, }