// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alerts } from "./Alerts";

export interface IncidentsJoined { id: number, result: string, started_at: string, updated_at: string, resolved_at: string | null, host_uuid: string, hostname: string, status: number, severity: number, alerts_id: bigint, cid: string, alert: Alerts | null, }