// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LoadAvg { id: bigint, one: number, five: number, fifteen: number, host_uuid: string, created_at: string, }