// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Swap { id: bigint, total: bigint, free: bigint, used: bigint, host_uuid: string, created_at: string, }